export {default as Main} from './main'
export {default as Memu} from './memu'
export {default as Identification} from './identification'
export {default as BirthDate} from './identification/birthDate'
export {default as ChartNumber} from './identification/chartNumber'
